apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DSSP-TargetP-13
  annotations:
    github.com/project-slug: BackstageSSPPoC/DSSP-TargetP-13
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: Backstage_SSP_PoC/DSSP-TargetP-13/main
    argocd/app-name: DSSP-TargetP-13.toLowerCase()-qa
    backstage.io/kubernetes-id: DSSP-TargetP-13.toLowerCase()
    sonarqube.org/project-key: DSSP-TargetP-13
spec:
  type: service
  lifecycle: qa
  owner: user:default/guest